const routes = Object.freeze({
  homeBottomTab: "Home",
  home: "home",
  nutration: "Nutration",
  meditation: "Meditation",
  meditationStack: "meditation",
  meditationDetails: "meditation-details",
  workoutsDetails: "workouts-details",
  workouts: "Workouts",
  workoutsStack: "workouts",
  fitness: "Fitness",
  cardio: "Cardio",
  loginDrawer: "Login",
  login: "login",
  signup: "Signup",
  profile: "Profile",
  settings: "Settings",
  editProfile: "Edit",
  notifications: "Notific",
  bmiTest: "BMI",
  languages: "Lang",
  help: "Help",
  helpContent: "Help Content",
  helpNavigation: "help",
});

export default routes;
